name: chatwork
version: 0.1.3.6
synopsis: The ChatWork API in Haskell
description: See README at <https://github.com/matsubara0507/chatwork#readme>
maintainer: MATSUBARA Nobutada
author: MATSUBARA Nobutada
copyright: 2017-2018 MATSUBARA Nobutada
license: MIT
github: matsubara0507/chatwork
category: Web

ghc-options: -Wall

dependencies:
  - base >=4.7 && <5
  - aeson >=1.4
  - aeson-casing >=0.1
  - bytestring >=0.10
  - data-default-class >=0.1
  - http-api-data >=0.4
  - http-client >=0.5
  - http-types >=0.12
  - req >=1.2
  - text >=1.2

library:
  source-dirs: src

# executables:
#   sample-exe:
#     source-dirs: sample
#     main: Main.hs
#     dependencies:
#       - chatwork

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - servant-server >=0.9.1.1 && <0.15
      - warp >=3.2.11 && <3.3
      - hspec >=2.4.1 && <2.6
